# Generated by Django 3.2.9 on 2021-11-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='users',
            field=models.ManyToManyField(related_name='reviews', through='reviews.Like', to='users.User'),
        ),
    ]
